# Generated by Django 3.0.7 on 2020-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pipe_Outside_Diameter', models.IntegerField(default='10.75')),
                ('Pipe_Wall_Thickness', models.IntegerField(default='0.5')),
                ('Pipe_Density', models.IntegerField(default='490')),
                ('Corrosion_Allowance', models.IntegerField(default='0.125')),
                ('Coating_No', models.IntegerField(default='1')),
                ('Description', models.CharField(default='FBE', max_length=50)),
                ('External_Coating_Thickness', models.IntegerField(default='0.0118110236220472')),
                ('Density', models.IntegerField(default='81.156348')),
                ('Installation_Empty', models.IntegerField(default='0')),
                ('Flooded', models.IntegerField(default='64')),
                ('Hydrotest', models.IntegerField(default='64.7')),
            ],
        ),
    ]
