# Generated by Django 3.0.7 on 2020-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='Corrosion_Allowance',
            field=models.FloatField(default='0.125'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Density',
            field=models.FloatField(default='81.156348'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='External_Coating_Thickness',
            field=models.FloatField(default='0.0118110236220472'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Flooded',
            field=models.FloatField(default='64'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Hydrotest',
            field=models.FloatField(default='64.7'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Pipe_Density',
            field=models.FloatField(default='490'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Pipe_Outside_Diameter',
            field=models.FloatField(default='10.75'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='Pipe_Wall_Thickness',
            field=models.FloatField(default='0.5'),
        ),
    ]
