# Generated by Django 3.0.7 on 2020-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0002_auto_20200911_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='Inside_Radius',
            field=models.FloatField(default='0.00'),
        ),
    ]
