# Generated by Django 3.0.7 on 2020-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0003_pipe_inside_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='Pipe_Outside_Radius',
            field=models.FloatField(default='0.00'),
        ),
    ]
