# Generated by Django 3.0.7 on 2020-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0004_pipe_pipe_outside_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='Inside_Radius',
            new_name='Buoyant_Force_per_Unit_Length',
        ),
        migrations.AddField(
            model_name='pipe',
            name='Coating_1_Wt_per_Unit_Length_in_Air',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Contents_Wt_Per_Unit_Length_in_Air',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Outer_Radius_of_Coating',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Pipe_Inside_Radius',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Pipe_Weight_per_Unit_Length',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Subm_Specific_Gravity_with_respect_to_SW',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Submerged_Weight_per_Unit_Length',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Total_Pipeline_Outside_Diameter',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Total_Weight_per_Unit_Length_in_Air',
            field=models.FloatField(default='0.00'),
        ),
    ]
