# Generated by Django 3.0.7 on 2020-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0005_auto_20200911_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='Buoyant_Force_per_Unit_Length',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Coating_1_Wt_per_Unit_Length_in_Air',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Contents_Wt_Per_Unit_Length_in_Air',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Outer_Radius_of_Coating',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Pipe_Inside_Radius',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Pipe_Outside_Radius',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Pipe_Weight_per_Unit_Length',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Subm_Specific_Gravity_with_respect_to_SW',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Submerged_Weight_per_Unit_Length',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Total_Pipeline_Outside_Diameter',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='Total_Weight_per_Unit_Length_in_Air',
        ),
    ]
